import "server-only"

import { apiFetch } from "@/lib/api"

export type UploadLink = { url: string; fileAwsKey: string }

/**
 * Presigned S3 PUT URL, generated by the orders service (the only microservice with
 * AwsS3Module wired up today — shared by every admin upload flow, not just orders). The
 * caller PUTs the file bytes directly to `url`, then persists the resulting `fileAwsKey`.
 */
export function getUploadLink(fileKey?: string) {
  return apiFetch<UploadLink>("orders", "/orders/get-upload-link", {
    method: "POST",
    body: { fileKey },
  })
}
